sudo: required
services: 
    - docker

before-install:
    - docker build -t aymanacc/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true aymanacc/react-test npm test

after-success:
    - docker build -t aymanacc/multi-client ./client
    - docker build -t aymanacc/multi-server ./server
    - docker build -t aymanacc/multi-worker ./worker
    - docker build -t aymanacc/multi-nginx ./nginx
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push aymanacc/multi-client
    - docker push aymanacc/multi-server
    - docker push aymanacc/multi-worker
    - docker push aymanacc/multi-nginx

